#!/bin/bash

port_opts='--grpc-port 40401 --grpc-port-internal 40402'

if [[ $# -ne 1 ]]; then
	echo "Usage: $0 <contract-file>" >&2
	exit 1
fi

contract="$1"

while :
do
	sleep $(shuf -n1 -i30-90)

	echo "Proposing contract $contract"

	./bin/rnode $port_opts deploy \
		--from 0x1 \
		--phlo-limit 1000000 \
		--phlo-price 1 \
		--nonce 0 \
		$contract

	sleep 5

	if [[ $? -eq 0 ]]; then
		./bin/rnode $port_opts propose
	fi
done
