#!/bin/bash

port_opts='--grpc-port 40401 --grpc-port-internal 40402'

if [[ $# -ne 1 ]]; then
	echo "Usage: $0 <contract-file>" >&2
	exit 1
fi

contract="$1"

while :
do
	sleep $(shuf -n1 -i30-90)

	echo "Deploying contract $contract"

	./bin/rnode $port_opts deploy \
		--from 0x1 \
		--phlo-limit 1000000 \
		--phlo-price 1 \
		--nonce 0 \
		$contract

	ret=$?
	if [[ $ret -eq 0 ]]; then
		sleep 5

		echo "Proposing"
		./bin/rnode $port_opts propose

		ret=$?
		if [[ $ret -eq 0 ]]; then
			echo "Propose succeeded"
		else
			echo "Propose failed ($ret)"
		fi
	else
		echo "Deploy failed ($ret)"
	fi
done
