- name: Install packages required by Docker CE Apt repository
  package: name={{ item }} state=present
  with_items:
  - apt-transport-https
  - ca-certificates
  - gnupg2
  - software-properties-common

- name: Add Docker CE Apt repository GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker CE Apt repository source
  apt_repository:
    repo: deb https://download.docker.com/linux/debian stretch stable
    state: present

- name: Install Docker packages
  package: name={{ item }} state=present
  with_items:
  - docker-ce
  - docker-compose
  - python-docker
  - python3-docker
